### ISSUE TITLE
Type Error: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ChemistKieran** [Augus1999/mol2chemfigPy3#1]
Hi, I get the following error when running as a python package or from command line. 
I've tried running on python 3.8 & 3.7 on Linux and Windows. 
~~~{
Traceback (most recent call last):
  File "/home/directory/mol2chemfig.py", line 2, in <module>
    from mol2chemfigPy3 import mol2chemfigpy3
  File "/home/directory/.local/lib/python3.8/site-packages/mol2chemfigPy3/__init__.py", line 9, in <module>
    from .main import main
  File "/home/directory/.local/lib/python3.8/site-packages/mol2chemfigPy3/main.py", line 12, in <module>
    from .processor import process
  File "/home/directory/.local/lib/python3.8/site-packages/mol2chemfigPy3/processor.py", line 11, in <module>
    from . import common, options, molecule
  File "/home/directory/.local/lib/python3.8/site-packages/mol2chemfigPy3/molecule.py", line 8, in <module>
    from .atom import Atom
  File "/home/directory/.local/lib/python3.8/site-packages/mol2chemfigPy3/atom.py", line 15, in <module>
    class Atom:
  File "/home/directory/.local/lib/python3.8/site-packages/mol2chemfigPy3/atom.py", line 51, in Atom
    neighbors: list[int]):
TypeError: 'type' object is not subscriptable

~~~

I also get the following on my linter pointing at the typing (line 51, Atom.py):
~~~{
subscript for type tuple will generate runtime exception; enclose type annotation in quotes

~~~

-- Thanks

**Comment by Augus1999** [comment]
It's very weird that some python interpreter try to interpret the codes of type hints differently. I personally haven't encountered your problem both on my laptop (Windows) and remote machine (Linux), but now I replaced these `list` `tuple` etc to `typing.List` `typing.Tuple` which I think will solve your issue.

**Comment by ChemistKieran** [comment]
Perfect  ~ thank you! 

(and thanks for updating mol2chemfig to python 3 - it's really helpful)
